blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/withrvr/typerush/discussions
    about: Have an open-ended question, idea, or want to chat? Use Discussions.
